version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - echo Build started on `date`
     - aws s3 sync --delete . s3://codebuild-test-bucket-new
 post_build:
   commands:
     - echo Build completed on 'date'
